### ISSUE TITLE
Add a way to choose libraries from a graphical list

### ISSUE THREAD

**Issue by AdamantPenguin** [AdamantPenguin/snaplibs#1]
Currently, to import a library you have to know its name. This isn't great: let's say you want to use a file open dialogue but you don't know what libraries can do that. As it is now, you would need to go to the list of libraries in your browser and use the find tool to search it. What should be added is a GUI that shows the libraries with their metadata _inside the extension_ which you can search to find a library, then click to import it (or similar).

### Task list
- [x] Create a new branch
- [x] Create the GUI (probably as a webpage opened in a new window)
- [x] Add a button to the extension pop-up which opens the GUI
- [x] Add lists etc. to the GUI
- [x] Add a search feature to the GUI
- [x] Add import functionality (can't use the other dialog cos it closes itself)
- [x] Finishing touches
- [x] Create pull request and merge
